#! /bin/bash

 print_num(){
	while [ $# -ne 0 ]
  	      do 
                 echo -e "$1--\c"
                 shift
             done
          echo -e '\n'
	    }


   echo the funtion is under task:
   
   print_num i an wang zhen who are you

