#!/bin/bash
#
#
#get_input(){
#   while true ; do
#      local param="$1"
#      local temp=""
#      local mytemp=""
#      read mytemp
#
#      temp=${mytemp%%,*}
#      eval $param="'$temp'"
#      [ "$temp" = "$mytemp" ] &&  return || echo failed
#    done
#}
#
##echo $(get_input)
#
# get_input succ
#
# echo $succ
#

num=1
let num++
echo $num


if [ $num eq 2 ] ; then
	cut -d , -f 2- ./tracks.cdb 
else
	cut -d , -f 1 ./tracks.cdb 
fi | more
exit 0
